# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d167b9ddc33b55b05d9cb4f320ee756d78b12b8a1cedbd7150602b605f1a48758feea0767fbe157d3762887f728970521adb0ee0e79d5cb30f92fa85fb63d0

test:
  secret_key_base: 9eb69eb9d786f1633ae914347f7c284960595d19a0ae2ab94c81df7cff43b881914618d984414b6fa3f926d9cbaca04535d63c435b0d85c395b49d09a1c6919c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
